package com.link.shortlinkx.controller;

import com.link.shortlinkx.dto.CreateShortUrlRequest;
import com.link.shortlinkx.dto.ShortUrlResponse;
import com.link.shortlinkx.service.UrlService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.net.URI;
import java.util.List;

@RestController
@RequestMapping("/api/v1")
@RequiredArgsConstructor
@Tag(name = "URLs", description = "URL Shortener and redirection controller")
public class UrlController {

    private final UrlService urlService;

    @PostMapping("/shorten")
    @Operation(summary = "Shorten a URL", description = "Creates a base62 shortcode for the given original long URL and associates it with the authenticated user ID forwarded by the gateway.")
    public ResponseEntity<ShortUrlResponse> shorten(
            @RequestBody @Valid CreateShortUrlRequest request,
            @RequestHeader(value = "X-User-Id", required = false) Long userId) {

        Long effectiveUserId = (userId != null) ? userId : 0L;
        return ResponseEntity.ok(
                urlService.shortenUrl(request, effectiveUserId)
        );
    }

    @GetMapping("/{shortCode}")
    @Operation(summary = "Redirect shortcode", description = "Resolves a shortcode into its original URL target and executes an HTTP 302 redirect.")
    public ResponseEntity<Void> redirect(
            @PathVariable String shortCode,
            @RequestHeader(value = "X-Forwarded-For", required = false) String xForwardedFor,
            @RequestHeader(value = "Referer", required = false) String referrer,
            @RequestHeader(value = "User-Agent", required = false) String userAgent,
            HttpServletRequest request) {

        String ipAddress = (xForwardedFor != null) ? xForwardedFor : request.getRemoteAddr();
        String originalUrl = urlService.getOriginalUrlAndRecordClick(shortCode, ipAddress, referrer, userAgent);

        HttpHeaders headers = new HttpHeaders();
        headers.setLocation(URI.create(originalUrl));

        return new ResponseEntity<>(
                headers,
                HttpStatus.FOUND
        );
    }

    @GetMapping("/urls")
    @Operation(summary = "Get user link history", description = "Fetches the history of all shortened URLs generated by the authenticated user.")
    public ResponseEntity<List<ShortUrlResponse>> getUrlHistory(
            @RequestHeader("X-User-Id") Long userId) {
        
        return ResponseEntity.ok(
                urlService.getUrlsByUserId(userId)
        );
    }
}